/** Hospitais públicos/SUS — espelho de hospitais_sao_paulo_sus.py (backend). */
export const HOSPITAIS_SAOPAULO_SUS = [
  'Hospital das Clínicas da FMUSP',
  'Instituto do Câncer do Estado de São Paulo (ICESP)',
  'Instituto do Coração (InCor-HC-FMUSP)',
  'Instituto da Criança do HC-FMUSP',
  'Instituto de Infectologia Emílio Ribas',
  'Instituto de Psiquiatria do Hospital das Clínicas (IPq-HC)',
  'Instituto Central do Hospital das Clínicas (ICHC)',
  'Instituto de Ortopedia e Traumatologia (IOT-HC)',
  'Hospital São Paulo (UNIFESP)',
  'Hospital Universitário da USP (HU-USP)',
  "Hospital Municipal Dr. Moyses Deutsch (M'Boi Mirim)",
  'Hospital Municipal Dr. Arthur Ribeiro de Saboya',
  'Hospital Municipal Menino Jesus',
  'Hospital Municipal Vila Santa Catarina',
  'Hospital Municipal Vila Nova Cachoeirinha',
  'Hospital Municipal Dr. José Soares de Oliveira (Barueri)',
  'Hospital Geral de Pirajussara (Embu das Artes)',
  'Hospital Municipal Tide Setúbal (São Bernardo do Campo)',
  'Hospital Municipal Dr. Sinval Amaral (Guarulhos)',
  'Hospital Municipal Dr. Helio Beltrão (Mogi das Cruzes)',
  'Hospital Municipal Dr. Adão Pereira Nunes (Duque de Caxias)',
  'Hospital Municipal Dr. Nelson Moraes dos Santos (Diadema)',
  'Hospital Municipal Dr. Osvaldo Cruz',
  'Hospital Municipal Dr. Cândido Ferreira (Ferraz de Vasconcelos)',
  'Hospital Municipal Dr. Akira Tada (Santo André)',
  'Hospital Municipal Dr. David Capistrano da Costa Filho (Carapicuíba)',
  'Hospital Municipal Dr. Guido Guidi (Suzano)',
  'Hospital Municipal Dr. Christovão da Gama (Santo André)',
  'Hospital Municipal Dr. Jayme dos Santos Neves (São Vicente)',
  'Hospital Municipal Dr. Henrique da Silva (Osasco)',
  'Hospital Municipal Dr. Francisco Morato',
  'Hospital Municipal Dr. Moacyr Rodrigues do Lago (Embu-Guaçu)',
  'Hospital Municipal Dr. Manoel Bifulco (Itaquaquecetuba)',
  'Hospital Municipal Dr. Osório de Almeida (Itapevi)',
  'Hospital Municipal Dr. José de Carvalho Florence (São José dos Campos)',
  'Hospital Municipal Dr. Mário Gatti (Campinas)',
  'Outros',
];
