"""schema inicial

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-05-27 01:37:19.465634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status_assinatura', sa.String(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('bloqueado_em', sa.DateTime(), nullable=True),
    sa.Column('dias_tolerancia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motivos_inativacao',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('origens_encaminhamento',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quartos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo_publico', sa.String(), nullable=False),
    sa.Column('modalidade', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('perfil_acesso', sa.String(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('orgao_emissor', sa.String(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('nacionalidade', sa.String(), nullable=True),
    sa.Column('naturalidade', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('conselho_profissional', sa.String(), nullable=True),
    sa.Column('numero_conselho', sa.String(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('motivo_desligamento', sa.Text(), nullable=True),
    sa.Column('observacoes_profissionais', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login_em', sa.DateTime(), nullable=True),
    sa.Column('inativado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por_id', sa.String(), nullable=True),
    sa.Column('atualizado_por_id', sa.String(), nullable=True),
    sa.Column('inativado_por_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['inativado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_instituicao_id'), 'usuarios', ['instituicao_id'], unique=False)
    op.create_table('avisos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('remetente_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('classificacao', sa.String(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('destino_tipo', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('valido_ate', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('cancelado_por_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fechamentos_mensais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fechado_por_id', sa.String(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('reaberto_por_id', sa.String(), nullable=True),
    sa.Column('reaberto_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_reabertura', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fechado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['reaberto_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocolo')
    )
    op.create_table('leitos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quarto_id', sa.String(), nullable=False),
    sa.Column('identificacao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aviso_destinatarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aviso_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('lido', sa.Boolean(), nullable=True),
    sa.Column('lido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aviso_id'], ['avisos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conviventes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('numero_institucional', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('motivo_inativacao_id', sa.String(), nullable=True),
    sa.Column('origem_encaminhamento_id', sa.String(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('leito_id', sa.String(), nullable=True),
    sa.Column('tecnico_id', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('nome_social', sa.String(), nullable=True),
    sa.Column('identidade_genero', sa.String(), nullable=True),
    sa.Column('orientacao_sexual', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('naturalidade', sa.String(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('escolaridade', sa.String(), nullable=True),
    sa.Column('telefone_celular', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('nome_mae', sa.String(), nullable=True),
    sa.Column('nome_pai', sa.String(), nullable=True),
    sa.Column('numero_sisa', sa.String(), nullable=True),
    sa.Column('numero_nis', sa.String(), nullable=True),
    sa.Column('status_cadunico', sa.String(), nullable=True),
    sa.Column('programas_beneficios', sa.Text(), nullable=True),
    sa.Column('possui_renda', sa.Boolean(), nullable=True),
    sa.Column('renda_mensal', sa.Float(), nullable=True),
    sa.Column('contato_emergencia_nome', sa.String(), nullable=True),
    sa.Column('contato_emergencia_telefone', sa.String(), nullable=True),
    sa.Column('observacoes_saude', sa.Text(), nullable=True),
    sa.Column('email_pessoal', sa.String(), nullable=True),
    sa.Column('senha_email', sa.String(), nullable=True),
    sa.Column('senha_govbr', sa.String(), nullable=True),
    sa.Column('egresso_prisional', sa.Boolean(), nullable=True),
    sa.Column('usa_tornozeleira', sa.Boolean(), nullable=True),
    sa.Column('medidas_protetivas', sa.Text(), nullable=True),
    sa.Column('acompanhamento_caps', sa.String(), nullable=True),
    sa.Column('uso_substancias', sa.Text(), nullable=True),
    sa.Column('transtorno_mental', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['leito_id'], ['leitos.id'], ),
    sa.ForeignKeyConstraint(['motivo_inativacao_id'], ['motivos_inativacao.id'], ),
    sa.ForeignKeyConstraint(['origem_encaminhamento_id'], ['origens_encaminhamento.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conviventes_numero_institucional'), 'conviventes', ['numero_institucional'], unique=False)
    op.create_table('documentos_conviventes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias_conviventes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=False),
    sa.Column('usuario_criador_id', sa.String(), nullable=False),
    sa.Column('tecnico_responsavel_id', sa.String(), nullable=True),
    sa.Column('tipo_ocorrencia', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=True),
    sa.Column('requer_acao_tecnica', sa.Boolean(), nullable=True),
    sa.Column('status_resolucao', sa.String(), nullable=True),
    sa.Column('parecer_tecnico', sa.Text(), nullable=True),
    sa.Column('data_resolucao', sa.DateTime(), nullable=True),
    sa.Column('usuario_resolutor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['tecnico_responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_criador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_resolutor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_rotina',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('tipo_registro', sa.String(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('retorno_rapido', sa.Boolean(), nullable=True),
    sa.Column('justificativa_retorno_rapido', sa.Text(), nullable=True),
    sa.Column('foi_editado', sa.Boolean(), nullable=True),
    sa.Column('editado_por_id', sa.String(), nullable=True),
    sa.Column('editado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_edicao', sa.Text(), nullable=True),
    sa.Column('tipo_registro_original', sa.String(), nullable=True),
    sa.Column('data_registro_original', sa.DateTime(), nullable=True),
    sa.Column('cancelado', sa.Boolean(), nullable=True),
    sa.Column('cancelado_por_id', sa.String(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['editado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sisa_lancamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lancado_por_id', sa.String(), nullable=False),
    sa.Column('lancado_em', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['lancado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interacoes_ocorrencias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ocorrencia_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo_interacao', sa.String(), nullable=True),
    sa.Column('data_interacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencias_conviventes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observadores_ocorrencias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ocorrencia_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('data_marcacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencias_conviventes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observadores_ocorrencias')
    op.drop_table('interacoes_ocorrencias')
    op.drop_table('sisa_lancamentos')
    op.drop_table('registros_rotina')
    op.drop_table('ocorrencias_conviventes')
    op.drop_table('documentos_conviventes')
    op.drop_index(op.f('ix_conviventes_numero_institucional'), table_name='conviventes')
    op.drop_table('conviventes')
    op.drop_table('aviso_destinatarios')
    op.drop_table('leitos')
    op.drop_table('fechamentos_mensais')
    op.drop_table('avisos')
    op.drop_index(op.f('ix_usuarios_instituicao_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('quartos')
    op.drop_table('origens_encaminhamento')
    op.drop_table('motivos_inativacao')
    op.drop_table('instituicoes')
    # ### end Alembic commands ###
