"""adiciona retorno rapido rotina

Revision ID: 1074af39c9ef
Revises: 9d6844e5b19a
Create Date: 2026-05-20 20:29:55.933249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1074af39c9ef'
down_revision: Union[str, Sequence[str], None] = '9d6844e5b19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_rotina', sa.Column('retorno_rapido', sa.Boolean(), nullable=True))
    op.add_column('registros_rotina', sa.Column('justificativa_retorno_rapido', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('registros_rotina', 'justificativa_retorno_rapido')
    op.drop_column('registros_rotina', 'retorno_rapido')
    # ### end Alembic commands ###
