"""schema atual do sistema operacional

Revision ID: 4ec43e6c7a15
Revises: 0001_initial_schema
Create Date: 2026-06-05 00:26:57.944386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec43e6c7a15'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    dialect_name = op.get_bind().dialect.name

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_legado_siat',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=True),
    sa.Column('origem_informacao', sa.String(), nullable=False),
    sa.Column('arquivo_origem', sa.String(), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('pagina_origem', sa.Integer(), nullable=True),
    sa.Column('sequencia_origem', sa.Integer(), nullable=True),
    sa.Column('data_original', sa.Date(), nullable=True),
    sa.Column('data_original_texto', sa.String(), nullable=True),
    sa.Column('operador_origem', sa.String(), nullable=True),
    sa.Column('titulo_original', sa.String(), nullable=True),
    sa.Column('nome_identificado', sa.String(), nullable=True),
    sa.Column('tipo_sugerido', sa.String(), nullable=True),
    sa.Column('status_revisao', sa.String(), nullable=True),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('observacoes_revisao', sa.Text(), nullable=True),
    sa.Column('importado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_legado_siat_ano_origem'), 'historico_legado_siat', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_arquivo_origem'), 'historico_legado_siat', ['arquivo_origem'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_data_original'), 'historico_legado_siat', ['data_original'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_instituicao_id'), 'historico_legado_siat', ['instituicao_id'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_nome_identificado'), 'historico_legado_siat', ['nome_identificado'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_operador_origem'), 'historico_legado_siat', ['operador_origem'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_status_revisao'), 'historico_legado_siat', ['status_revisao'], unique=False)
    op.create_index(op.f('ix_historico_legado_siat_tipo_sugerido'), 'historico_legado_siat', ['tipo_sugerido'], unique=False)
    op.create_table('chat_conversas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('criado_por_id', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversas_instituicao_id'), 'chat_conversas', ['instituicao_id'], unique=False)
    op.create_table('sisa_importacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('importado_em', sa.DateTime(), nullable=True),
    sa.Column('total_linhas', sa.Integer(), nullable=True),
    sa.Column('total_vinculados', sa.Integer(), nullable=True),
    sa.Column('total_nao_encontrados', sa.Integer(), nullable=True),
    sa.Column('total_divergencias', sa.Integer(), nullable=True),
    sa.Column('total_alertas_criticos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_mensagens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversa_id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('remetente_id', sa.String(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['chat_conversas.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_mensagens_conversa_id'), 'chat_mensagens', ['conversa_id'], unique=False)
    op.create_index(op.f('ix_chat_mensagens_criado_em'), 'chat_mensagens', ['criado_em'], unique=False)
    op.create_index(op.f('ix_chat_mensagens_instituicao_id'), 'chat_mensagens', ['instituicao_id'], unique=False)
    op.create_index(op.f('ix_chat_mensagens_remetente_id'), 'chat_mensagens', ['remetente_id'], unique=False)
    op.create_table('chat_participantes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversa_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_lido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['chat_conversas.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_participantes_conversa_id'), 'chat_participantes', ['conversa_id'], unique=False)
    op.create_index(op.f('ix_chat_participantes_instituicao_id'), 'chat_participantes', ['instituicao_id'], unique=False)
    op.create_index(op.f('ix_chat_participantes_usuario_id'), 'chat_participantes', ['usuario_id'], unique=False)
    op.create_table('historicos_conviventes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('historico_legado_id', sa.String(), nullable=True),
    sa.Column('origem_informacao', sa.String(), nullable=False),
    sa.Column('data_origem', sa.Date(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['historico_legado_id'], ['historico_legado_siat.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_conviventes_convivente_id'), 'historicos_conviventes', ['convivente_id'], unique=False)
    op.create_index(op.f('ix_historicos_conviventes_data_origem'), 'historicos_conviventes', ['data_origem'], unique=False)
    op.create_index(op.f('ix_historicos_conviventes_instituicao_id'), 'historicos_conviventes', ['instituicao_id'], unique=False)
    op.create_table('registros_pia',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('registro_pai_id', sa.String(), nullable=True),
    sa.Column('tipo_registro', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('subtitulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('encaminhamentos', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['registro_pai_id'], ['registros_pia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sisa_divergencias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('importacao_id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=True),
    sa.Column('numero_sisa', sa.String(), nullable=False),
    sa.Column('nome_convivente', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias_sisa_anterior', sa.Integer(), nullable=True),
    sa.Column('dias_sisa_atual', sa.Integer(), nullable=False),
    sa.Column('dias_sisa_delta', sa.Integer(), nullable=True),
    sa.Column('dias_carecore', sa.Integer(), nullable=False),
    sa.Column('diferenca', sa.Integer(), nullable=True),
    sa.Column('dias_carecore_lista', sa.Text(), nullable=True),
    sa.Column('resumo_carecore_json', sa.Text(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['sisa_importacoes.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sisa_presencas_importadas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('importacao_id', sa.String(), nullable=False),
    sa.Column('instituicao_id', sa.String(), nullable=False),
    sa.Column('convivente_id', sa.String(), nullable=True),
    sa.Column('numero_sisa', sa.String(), nullable=False),
    sa.Column('nome_planilha', sa.String(), nullable=False),
    sa.Column('nome_social_planilha', sa.String(), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('data_vinculacao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('dias_permanencia', sa.Integer(), nullable=False),
    sa.Column('status_vinculo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['convivente_id'], ['conviventes.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['sisa_importacoes.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conviventes', sa.Column('inativado_em', sa.DateTime(), nullable=True))
    op.add_column('conviventes', sa.Column('tem_mandado_prisao', sa.Boolean(), nullable=True))
    op.add_column('documentos_conviventes', sa.Column('sensivel', sa.Boolean(), nullable=True))
    op.add_column('instituicoes', sa.Column('organizacao_id', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('email', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('cep', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('logradouro', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('numero', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('complemento', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('bairro', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('cidade', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('uf', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('tipo_projeto', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('projeto_unico', sa.Boolean(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_logo_url', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_nome_exibicao', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_rodape_linha1', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_rodape_linha2', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_telefone', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_email', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('relatorio_site', sa.String(), nullable=True))
    op.add_column('instituicoes', sa.Column('historico_legado_ativo', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_instituicoes_organizacao_id'), 'instituicoes', ['organizacao_id'], unique=False)
    if dialect_name != 'sqlite':
        op.create_foreign_key('fk_instituicoes_organizacao_id', 'instituicoes', 'organizacoes', ['organizacao_id'], ['id'])
    op.add_column('ocorrencias_conviventes', sa.Column('convivente_autor_ocorrencia', sa.Boolean(), nullable=True))
    op.add_column('ocorrencias_conviventes', sa.Column('funcionario_envolvido_id', sa.String(), nullable=True))
    op.add_column('ocorrencias_conviventes', sa.Column('assinatura_convivente_metodo', sa.String(), nullable=True))
    op.add_column('ocorrencias_conviventes', sa.Column('assinatura_convivente_codigo', sa.String(), nullable=True))
    op.add_column('ocorrencias_conviventes', sa.Column('assinatura_convivente_validada_em', sa.DateTime(), nullable=True))
    op.add_column('ocorrencias_conviventes', sa.Column('prioridade', sa.String(), nullable=True))
    if dialect_name != 'sqlite':
        op.create_foreign_key('fk_ocorrencias_funcionario_envolvido_id', 'ocorrencias_conviventes', 'usuarios', ['funcionario_envolvido_id'], ['id'])
    op.add_column('registros_rotina', sa.Column('observacao', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('organizacao_id', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_usuarios_organizacao_id'), 'usuarios', ['organizacao_id'], unique=False)
    if dialect_name != 'sqlite':
        op.create_foreign_key('fk_usuarios_organizacao_id', 'usuarios', 'organizacoes', ['organizacao_id'], ['id'])
    op.execute(
        "INSERT INTO organizacoes (id, nome, cnpj, telefone, is_active, criado_em) "
        "SELECT i.id, i.nome_fantasia, i.cnpj, i.telefone, i.is_active, CURRENT_TIMESTAMP "
        "FROM instituicoes i "
        "WHERE i.organizacao_id IS NULL "
        "AND NOT EXISTS (SELECT 1 FROM organizacoes o WHERE o.id = i.id)"
    )
    op.execute("UPDATE instituicoes SET organizacao_id = id WHERE organizacao_id IS NULL")
    op.execute(
        "UPDATE usuarios SET organizacao_id = ("
        "SELECT i.organizacao_id FROM instituicoes i WHERE i.id = usuarios.instituicao_id"
        ") WHERE organizacao_id IS NULL"
    )
    op.execute(
        "UPDATE usuarios SET is_global = TRUE "
        "WHERE lower(email) = 'diretor@carecore.com'"
    )
    op.create_index('ix_registros_rotina_sisa_periodo', 'registros_rotina', ['instituicao_id', 'cancelado', 'data_registro', 'convivente_id', 'tipo_registro'], unique=False)
    op.create_index('ix_registros_rotina_ultimo_movimento', 'registros_rotina', ['instituicao_id', 'cancelado', 'tipo_registro', 'convivente_id', 'data_registro'], unique=False)
    op.create_index('ix_conviventes_instituicao_status', 'conviventes', ['instituicao_id', 'status'], unique=False)
    op.create_index('ix_conviventes_lista_resumo', 'conviventes', ['instituicao_id', 'status', 'nome_completo', 'numero_institucional'], unique=False)
    op.create_index('ix_sisa_lancamentos_instituicao_mes', 'sisa_lancamentos', ['instituicao_id', 'ano', 'mes', 'convivente_id'], unique=False)
    op.create_index('ix_sisa_importacoes_instituicao_data', 'sisa_importacoes', ['instituicao_id', 'data_referencia', 'importado_em'], unique=False)
    op.create_index('ix_instituicoes_organizacao', 'instituicoes', ['organizacao_id'], unique=False)
    op.create_index('ix_usuarios_organizacao', 'usuarios', ['organizacao_id', 'is_global'], unique=False)
    op.create_index('ix_sisa_presencas_numero_data', 'sisa_presencas_importadas', ['instituicao_id', 'numero_sisa', 'data_referencia'], unique=False)
    op.create_index('ix_sisa_divergencias_importacao_tipo', 'sisa_divergencias', ['instituicao_id', 'importacao_id', 'tipo', 'prioridade', 'status'], unique=False)
    op.create_index('ix_ocorrencias_dashboard', 'ocorrencias_conviventes', ['instituicao_id', 'status_resolucao', 'prioridade', 'tecnico_responsavel_id', 'data_ocorrencia'], unique=False)
    op.create_index('ix_historico_legado_filtros', 'historico_legado_siat', ['instituicao_id', 'ano_origem', 'data_original', 'tipo_sugerido', 'status_revisao'], unique=False)
    op.create_index('ix_historico_legado_busca_nome', 'historico_legado_siat', ['instituicao_id', 'nome_identificado', 'operador_origem'], unique=False)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_historico_legado_ordem "
        "ON historico_legado_siat (instituicao_id, data_original DESC, ano_origem DESC, pagina_origem, sequencia_origem)"
    )
    op.create_index('ix_historicos_conviventes_lookup', 'historicos_conviventes', ['instituicao_id', 'convivente_id', 'data_origem', 'criado_em'], unique=False)
    op.create_index('ix_quartos_instituicao', 'quartos', ['instituicao_id'], unique=False)
    op.create_index('ix_leitos_quarto_status', 'leitos', ['quarto_id', 'status'], unique=False)
    op.create_index('ix_chat_participantes_usuario', 'chat_participantes', ['instituicao_id', 'usuario_id', 'ativo', 'conversa_id'], unique=False)
    op.create_index('ix_chat_mensagens_conversa_data', 'chat_mensagens', ['conversa_id', 'criado_em'], unique=False)
    op.create_index('ix_chat_conversas_ordem', 'chat_conversas', ['instituicao_id', 'atualizado_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    dialect_name = op.get_bind().dialect.name

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_conversas_ordem', table_name='chat_conversas')
    op.drop_index('ix_chat_mensagens_conversa_data', table_name='chat_mensagens')
    op.drop_index('ix_chat_participantes_usuario', table_name='chat_participantes')
    op.drop_index('ix_leitos_quarto_status', table_name='leitos')
    op.drop_index('ix_quartos_instituicao', table_name='quartos')
    op.drop_index('ix_historicos_conviventes_lookup', table_name='historicos_conviventes')
    op.drop_index('ix_historico_legado_ordem', table_name='historico_legado_siat')
    op.drop_index('ix_historico_legado_busca_nome', table_name='historico_legado_siat')
    op.drop_index('ix_historico_legado_filtros', table_name='historico_legado_siat')
    op.drop_index('ix_ocorrencias_dashboard', table_name='ocorrencias_conviventes')
    op.drop_index('ix_sisa_divergencias_importacao_tipo', table_name='sisa_divergencias')
    op.drop_index('ix_sisa_presencas_numero_data', table_name='sisa_presencas_importadas')
    op.drop_index('ix_usuarios_organizacao', table_name='usuarios')
    op.drop_index('ix_instituicoes_organizacao', table_name='instituicoes')
    op.drop_index('ix_sisa_importacoes_instituicao_data', table_name='sisa_importacoes')
    op.drop_index('ix_sisa_lancamentos_instituicao_mes', table_name='sisa_lancamentos')
    op.drop_index('ix_conviventes_lista_resumo', table_name='conviventes')
    op.drop_index('ix_conviventes_instituicao_status', table_name='conviventes')
    op.drop_index('ix_registros_rotina_ultimo_movimento', table_name='registros_rotina')
    op.drop_index('ix_registros_rotina_sisa_periodo', table_name='registros_rotina')
    if dialect_name != 'sqlite':
        op.drop_constraint('fk_usuarios_organizacao_id', 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_organizacao_id'), table_name='usuarios')
    op.drop_column('usuarios', 'is_global')
    op.drop_column('usuarios', 'organizacao_id')
    op.drop_column('registros_rotina', 'observacao')
    if dialect_name != 'sqlite':
        op.drop_constraint('fk_ocorrencias_funcionario_envolvido_id', 'ocorrencias_conviventes', type_='foreignkey')
    op.drop_column('ocorrencias_conviventes', 'prioridade')
    op.drop_column('ocorrencias_conviventes', 'assinatura_convivente_validada_em')
    op.drop_column('ocorrencias_conviventes', 'assinatura_convivente_codigo')
    op.drop_column('ocorrencias_conviventes', 'assinatura_convivente_metodo')
    op.drop_column('ocorrencias_conviventes', 'funcionario_envolvido_id')
    op.drop_column('ocorrencias_conviventes', 'convivente_autor_ocorrencia')
    if dialect_name != 'sqlite':
        op.drop_constraint('fk_instituicoes_organizacao_id', 'instituicoes', type_='foreignkey')
    op.drop_index(op.f('ix_instituicoes_organizacao_id'), table_name='instituicoes')
    op.drop_column('instituicoes', 'historico_legado_ativo')
    op.drop_column('instituicoes', 'relatorio_site')
    op.drop_column('instituicoes', 'relatorio_email')
    op.drop_column('instituicoes', 'relatorio_telefone')
    op.drop_column('instituicoes', 'relatorio_rodape_linha2')
    op.drop_column('instituicoes', 'relatorio_rodape_linha1')
    op.drop_column('instituicoes', 'relatorio_nome_exibicao')
    op.drop_column('instituicoes', 'relatorio_logo_url')
    op.drop_column('instituicoes', 'projeto_unico')
    op.drop_column('instituicoes', 'tipo_projeto')
    op.drop_column('instituicoes', 'uf')
    op.drop_column('instituicoes', 'cidade')
    op.drop_column('instituicoes', 'bairro')
    op.drop_column('instituicoes', 'complemento')
    op.drop_column('instituicoes', 'numero')
    op.drop_column('instituicoes', 'logradouro')
    op.drop_column('instituicoes', 'cep')
    op.drop_column('instituicoes', 'email')
    op.drop_column('instituicoes', 'organizacao_id')
    op.drop_column('documentos_conviventes', 'sensivel')
    op.drop_column('conviventes', 'tem_mandado_prisao')
    op.drop_column('conviventes', 'inativado_em')
    op.drop_table('sisa_presencas_importadas')
    op.drop_table('sisa_divergencias')
    op.drop_table('registros_pia')
    op.drop_index(op.f('ix_historicos_conviventes_instituicao_id'), table_name='historicos_conviventes')
    op.drop_index(op.f('ix_historicos_conviventes_data_origem'), table_name='historicos_conviventes')
    op.drop_index(op.f('ix_historicos_conviventes_convivente_id'), table_name='historicos_conviventes')
    op.drop_table('historicos_conviventes')
    op.drop_index(op.f('ix_chat_participantes_usuario_id'), table_name='chat_participantes')
    op.drop_index(op.f('ix_chat_participantes_instituicao_id'), table_name='chat_participantes')
    op.drop_index(op.f('ix_chat_participantes_conversa_id'), table_name='chat_participantes')
    op.drop_table('chat_participantes')
    op.drop_index(op.f('ix_chat_mensagens_remetente_id'), table_name='chat_mensagens')
    op.drop_index(op.f('ix_chat_mensagens_instituicao_id'), table_name='chat_mensagens')
    op.drop_index(op.f('ix_chat_mensagens_criado_em'), table_name='chat_mensagens')
    op.drop_index(op.f('ix_chat_mensagens_conversa_id'), table_name='chat_mensagens')
    op.drop_table('chat_mensagens')
    op.drop_table('sisa_importacoes')
    op.drop_index(op.f('ix_chat_conversas_instituicao_id'), table_name='chat_conversas')
    op.drop_table('chat_conversas')
    op.drop_index(op.f('ix_historico_legado_siat_tipo_sugerido'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_status_revisao'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_operador_origem'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_nome_identificado'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_instituicao_id'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_data_original'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_arquivo_origem'), table_name='historico_legado_siat')
    op.drop_index(op.f('ix_historico_legado_siat_ano_origem'), table_name='historico_legado_siat')
    op.drop_table('historico_legado_siat')
    op.drop_table('organizacoes')
    # ### end Alembic commands ###
