"""baseline inicial

Revision ID: 9d6844e5b19a
Revises: 
Create Date: 2026-05-20 11:09:09.290233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6844e5b19a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_rotina', sa.Column('foi_editado', sa.Boolean(), nullable=True))
    op.add_column('registros_rotina', sa.Column('editado_por_id', sa.String(), nullable=True))
    op.add_column('registros_rotina', sa.Column('editado_em', sa.DateTime(), nullable=True))
    op.add_column('registros_rotina', sa.Column('motivo_edicao', sa.Text(), nullable=True))
    op.add_column('registros_rotina', sa.Column('tipo_registro_original', sa.String(), nullable=True))
    op.add_column('registros_rotina', sa.Column('data_registro_original', sa.DateTime(), nullable=True))
    op.add_column('registros_rotina', sa.Column('cancelado', sa.Boolean(), nullable=True))
    op.add_column('registros_rotina', sa.Column('cancelado_por_id', sa.String(), nullable=True))
    op.add_column('registros_rotina', sa.Column('cancelado_em', sa.DateTime(), nullable=True))
    op.add_column('registros_rotina', sa.Column('motivo_cancelamento', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_rotina', 'motivo_cancelamento')
    op.drop_column('registros_rotina', 'cancelado_em')
    op.drop_column('registros_rotina', 'cancelado_por_id')
    op.drop_column('registros_rotina', 'cancelado')
    op.drop_column('registros_rotina', 'data_registro_original')
    op.drop_column('registros_rotina', 'tipo_registro_original')
    op.drop_column('registros_rotina', 'motivo_edicao')
    op.drop_column('registros_rotina', 'editado_em')
    op.drop_column('registros_rotina', 'editado_por_id')
    op.drop_column('registros_rotina', 'foi_editado')
    # ### end Alembic commands ###
